global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'static'
    static_configs:
      - targets: ['localhost:9090', '172.31.47.120:9100', '172.31.38.174:9100', '172.31.45.87:9100']
      
  - job_name: 'dynamic'
    ec2_sd_configs:
      - region: 'us-east-1'
        access_key: ${AWS_ACCESS_KEY_ID}
        secret_key: ${AWS_SECRET_ACCESS_KEY} 
        port: 9100
