global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIA54ECXSSUBJBYIPTH
        secret_key: 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
        port: 9100
