global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090', '172.31.42.189:9100', '172.31.40.94:9100']

scrape_configs:
  - job_name: 'prometheus'
    ec2_sd_configs:
      - region: us-east-1
        access_key: ${AWS_ACCESS_KEY_ID}
        secret_key: ${AWS_SECRET_ACCESS_KEY} 
        port: 9100
